<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        DB::table('product_categories')->insert([
            [
                'name' => 'Flowering',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Non flowering',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Indoor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Outdoor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Succulents',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Medicinal and so on',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);

        DB::table('products')->insert([
            [
                'product_category_id' => 1,
                'name' => 'Skip Cherry Laurel',
                'slug' => Str::slug('Skip Cherry Laurel'),
                'description' => 'Skip Laurel is well known for its hardiness. Other varieties of Laurel will brown in winter, with those lovely glossy leaves turning brown and ugly. If you live in cooler areas, such as zone 6, be careful to choose this variety for your garden. In those areas it will always go through the winter without browning, coming into the spring looking as healthy and fresh as it did in fall.',
                'content' => null,
                'price' => 59.50,
                'qty' => 25,
                'discount' => 63.05,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 6,
                'name' => 'Probiotic Root Stimulant',
                'slug' => Str::slug('Probiotic Root Stimulant'),
                'description' => 'Every one of the components in Probiotic Root Stimulant are supported by horticultural science, and we crafted this hand-blended mix from multiple ingredients chosen with the help of the latest scientific breakthroughs, and decades of experience. Every component has been proven to accelerate the establishment and adaption of newly-planted trees, so together they are the complete mixture every new tree needs.',
                'content' => null,
                'price' => 9.10,
                'qty' => 25,
                'discount' => 16.52,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 1,
                'name' => 'Little Gem Southern Magnolia',
                'slug' => Str::slug('Little Gem Southern Magnolia'),
                'description' => 'The Little Gem Southern Magnolia is a versatile plant that can be used in many different ways in the garden. Because of its smaller size, it makes a great specimen tree in the lawn for a smaller garden. It is gorgeous planted as a beautiful background to other shrubs and flowering plants. It also makes an elegant avenue, spaced out along a driveway in pairs, with one on either side. If you need a screen, this tree is ideal, since it stays compact, but is rapid growing, dense and evergreen, with the bonus of beautiful flowers.',
                'content' => null,
                'price' => 129.10,
                'qty' => 5,
                'discount' => 146.91,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 3,
                'name' => 'Aglaonema Jazzed Gems™ Dizzy Diamond',
                'slug' => Str::slug('Aglaonema Jazzed Gems Dizzy Diamond'),
                'description' => 'Aglaonema Jazzed Gems™ ‘Sapphire Suzanne’ is a showy houseplant displaying dark green leaves with leaf edges that glow reddish pink. The foliage is carried on lovely pale pink stems. Bright indirect light will bring out the best color in your home.',
                'content' => null,
                'price' => 32.71,
                'qty' => 5,
                'discount' => 39.23,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 6,
                'name' => 'Neem Oil',
                'slug' => Str::slug('Neem Oil'),
                'description' => 'Pure cold pressed neem oil Docneem is produced by cold pressing technology, keeping the original essence and has a strong smell to help repel and eliminate harmful insects extremely effectively. At the same time inhibits the development of eggs, pupae of pests. Limiting pests laying eggs, preventing the molting of harmful pests.',
                'content' => null,
                'price' => 15.91,
                'qty' => 5,
                'discount' => 19.22,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 5,
                'name' => 'Zig-Zag Cactus',
                'slug' => Str::slug('Zig-Zag Cactus'),
                'description' => 'Zig-Zag Cactus is an excellent choice for someone starting to care for houseplants. The succulent leaves hold moisture minimizing the need for frequent watering. The thin wavy leaves will cascade over the sides of the container, creating undulating waves of green ribbons. Provide the Zig Zag Cactus with over 6 hours of bright indirect sunlight daily and temperatures over 65°F to encourage it to grow.',
                'content' => null,
                'price' => 55.00,
                'qty' => 5,
                'discount' => 60.00,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 4,
                'name' => 'Karl Rosenfield Peony',
                'slug' => Str::slug('Karl Rosenfield Peony'),
                'description' => 'The Karl Rosenfield Peony is an herbaceous perennial plant, dying back to the ground each fall and returning in spring to quickly develop into a shrub-like bush, 2 to 3 feet tall and wide, with large, glossy green leaves divided into many pointed lobes. These stay beautiful and attractive all through summer and into fall, when they often turn shades of red and gold.',
                'content' => null,
                'price' => 69.50,
                'qty' => 12,
                'discount' => 83.23,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 2,
                'name' => 'Dracaena Ulises',
                'slug' => Str::slug('Dracaena Ulises'),
                'description' => 'Glossy and Glamorous, Ulises lances at your space with radiant green foliage banded with white striping. The compact arrangement of this dragon tree against a bright backdrop creates an atmosphere of sophistication and elegance, the perfect statement piece in an entrance or hallway. The multi-stem variety of this Dracaena displays individual plants at tiered heights creating a more structured and sculptural display.',
                'content' => null,
                'price' => 151.22,
                'qty' => 12,
                'discount' => 162.93,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 1,
                'name' => 'Olympic Fire Mountain Laurel',
                'slug' => Str::slug('Olympic Fire Mountain Laurel'),
                'description' => 'The Olympic Flame Mountain Laurel is an evergreen shrub with an upright, rounded form. In the garden, it will grow to 4 or 5 feet in height, and perhaps 4 feet wide – in a planter it will be smaller. Even when not in flower the foliage is excellent. The smooth oval leaves are glossy and leathery, between 3 and 5 inches long, and with an attractive wavy edge. The leaves give the plant a nice dense look, and it is attractive every day of the year. Older plants may develop a woody, gnarled base, which only adds to their appeal.',
                'content' => null,
                'price' => 64.80,
                'qty' => 12,
                'discount' => 60.93,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 6,
                'name' => 'Indoor Plant Mister',
                'slug' => Str::slug('Indoor Plant Mister'),
                'description' => 'Keep your plants looking and feeling fresh in style with a classically styled metal mister in a deep grey coating. Perfect for houseplants that crave humidity and a soft approach to watering. The super-fine mist of this must-have accessory will revitalise your plants with delicacy.',
                'content' => null,
                'price' => 99.10,
                'qty' => 12,
                'discount' => 100.88,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 2,
                'name' => 'Nellie Stevens Holly',
                'slug' => Str::slug('Nellie Stevens Holly'),
                'description' => 'The Nellie Stevens Holly is a large evergreen shrub with glossy, rich green foliage. It quickly grows into a large shrub that is conical in shape, between 15 and 25 feet tall and between 8 and 12 feet wide. It will naturally keep its foliage right to the ground for many, many years, which is very important in making a screen. The feature also makes it a great specimen plant, forming a beautiful upright plant with no need to plant anything beneath it.',
                'content' => null,
                'price' => 210.00,
                'qty' => 3,
                'discount' => 238.00,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 4,
                'name' => 'Austrian Black Pine',
                'slug' => Str::slug('Austrian Black Pine'),
                'description' => 'The Pinus nigra is most common throughout the Mediterranean forests and woodlands found around various European countries; they are most abundant in Turkey and the higher elevations of the South Apennine forests of Italy. As a young tree, the black pine retains a conical form and displays a strong growth rate; however as it ages the growth slows and the tree begins to take on a broader shape with slightly irregular branches. Its long, stiff dark green needles contrast beautifully against the tree’s dark brown to almost black bark.',
                'content' => null,
                'price' => 79.50,
                'qty' => 3,
                'discount' => 83.00,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 3,
                'name' => 'Calathea Peacock',
                'slug' => Str::slug('Calathea Peacock'),
                'description' => 'The Calathea Makoyana Peacock is native to Central and South America, including countries like Colombia and Venezuela. The plant is also known as Peacock or gerbera, and is one of the popular Calathea species grown indoors for its beautiful leaves and good shade tolerance. The leaves are oval or heart shaped, green with dark green veins, creating a beautiful vein pattern resembling a peacock eye. The leaves are about 20-30 cm in size on average and have a pale purple underside.',
                'content' => null,
                'price' => 34.90,
                'qty' => 3,
                'discount' => 41.00,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 6,
                'name' => 'All-Organic Complete Fertilizer',
                'slug' => Str::slug('All-Organic Complete Fertilizer'),
                'description' => 'Our carefully-crafted product delivers balanced levels of all three major plant nutrients. Put simply, Nitrogen (N) delivers green leaves and encourages stem growth. Phosphate (P) feeds the growing points of both roots and stems, encouraging extensive root development and branching, while Potassium (K) encourages blooming and fruit development, as well as giving resistance to pests, diseases and winter cold.',
                'content' => null,
                'price' => 7.50,
                'qty' => 3,
                'discount' => 8.20,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 6,
                'name' => 'Tree Staking Kit',
                'slug' => Str::slug('Tree Staking Kit'),
                'description' => 'Our Tree Stake Kit gives you everything you need to use correct methods easily and quickly, knowing you have done the right thing. In the kit you will find a broad woven strap, colored black for low visibility. This strap wraps around the stem, supporting it broadly so as not to scar the bark of young trees. It has three brass no-rusting eyelets for easy attachment of the ropes, which are also black, making them almost invisible once installed. The ropes are very strong, and made of woven polypropylene, so they will never rot and break.',
                'content' => null,
                'price' => 16.95,
                'qty' => 3,
                'discount' => 20.00,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 4,
                'name' => 'Royal Purple Smoke Tree',
                'slug' => Str::slug('Royal Purple Smoke Tree'),
                'description' => 'The Royal Purple Smoketree grows into a rounded bush upwards of 10 feet tall and at least as wide. Left to grow naturally it is a great way to fill a corner or an empty space in the garden. It can also be pruned to keep it smaller if needed, and also grown into a striking informal purple-leaved hedge or screen. The rounded leaves are 3 inches across, or even larger in pruned plants. In spring they emerge a brilliant purple-red color, and while some plants with colored leaves in spring simply turn dark green in summer, this does not happen with this bush.',
                'content' => null,
                'price' => 119.25,
                'qty' => 3,
                'discount' => 120.00,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_category_id' => 4,
                'name' => 'Golden Spirit Smoke Tree',
                'slug' => Str::slug('Golden Spirit Smoke Tree'),
                'description' => 'The Golden Spirit Smoketree is a round, full, deciduous shrub that if untrimmed will grow to between 8 and 15 feet tall and wide, depending on conditions, pruning, and age. That means one beautiful plant fills a lot of space, making it ideal for larger gardens and big beds. With simple trimming, it can be kept a lot smaller, so this is, without doubt, a plant for all gardens. It has branches right to the ground, and it makes a great specimen on a large lawn, or at the back of larger shrub beds. It is the perfect way to fill those awkward corners of your yard, or if planted as a screen it makes a striking informal hedge, blocking unsightly views and noise for all the outdoor months.',
                'content' => null,
                'price' => 133.88,
                'qty' => 3,
                'discount' => 152.37,
                'weight' => null,
                'sku' => Str::random(8),
                'featured' => true,
                'species' => "demo",
                'rate' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);

        DB::table('product_detail')->insert([
            [
                'product_id' => 1,
                'size' => 'M',
                'qty' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'size' => 'L',
                'qty' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'size' => 'XS',
                'qty' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('product_review')->insert([
            [
                'product_id' => 1,
                'user_id' => 1,
                'message' => 'Nice !',
                'score' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'user_id' => 1,
                'message' => 'Good !',
                'score' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'user_id' => 1,
                'message' => 'Nhu l !',
                'score' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('product_images')->insert([
            [
                'product_id' => 1,
                'path' => 'front/assets/img/product/product-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'path' => 'front/assets/img/product/product-1.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'path' => 'front/assets/img/product/product-1.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'path' => 'front/assets/img/product/product-1.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'path' => 'front/assets/img/product/product-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'path' => 'front/assets/img/product/product-2.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'path' => 'front/assets/img/product/product-2.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'path' => 'front/assets/img/product/product-2.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'path' => 'front/assets/img/product/product-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'path' => 'front/assets/img/product/product-3.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'path' => 'front/assets/img/product/product-3.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'path' => 'front/assets/img/product/product-3.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'path' => 'front/assets/img/product/product-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'path' => 'front/assets/img/product/product-4.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'path' => 'front/assets/img/product/product-4.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'path' => 'front/assets/img/product/product-4.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'path' => 'front/assets/img/product/product-5.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'path' => 'front/assets/img/product/product-5.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'path' => 'front/assets/img/product/product-6.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'path' => 'front/assets/img/product/product-6.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'path' => 'front/assets/img/product/product-6.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'path' => 'front/assets/img/product/product-6.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'path' => 'front/assets/img/product/product-7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'path' => 'front/assets/img/product/product-7.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'path' => 'front/assets/img/product/product-7.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'path' => 'front/assets/img/product/product-7.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'path' => 'front/assets/img/product/product-8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'path' => 'front/assets/img/product/product-8.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'path' => 'front/assets/img/product/product-8.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'path' => 'front/assets/img/product/product-8.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'path' => 'front/assets/img/product/product-9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'path' => 'front/assets/img/product/product-9.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'path' => 'front/assets/img/product/product-9.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 9,
                'path' => 'front/assets/img/product/product-9.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'path' => 'front/assets/img/product/product-10.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'path' => 'front/assets/img/product/product-10.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 10,
                'path' => 'front/assets/img/product/product-10.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'path' => 'front/assets/img/product/product-11.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'path' => 'front/assets/img/product/product-11.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'path' => 'front/assets/img/product/product-11.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'path' => 'front/assets/img/product/product-11.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 12,
                'path' => 'front/assets/img/product/product-12.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 12,
                'path' => 'front/assets/img/product/product-12.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 12,
                'path' => 'front/assets/img/product/product-12.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 12,
                'path' => 'front/assets/img/product/product-12.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 13,
                'path' => 'front/assets/img/product/product-13.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 13,
                'path' => 'front/assets/img/product/product-13.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 13,
                'path' => 'front/assets/img/product/product-13.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 14,
                'path' => 'front/assets/img/product/product-14.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 14,
                'path' => 'front/assets/img/product/product-14.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 14,
                'path' => 'front/assets/img/product/product-14.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 14,
                'path' => 'front/assets/img/product/product-14.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 15,
                'path' => 'front/assets/img/product/product-15.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 15,
                'path' => 'front/assets/img/product/product-15.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 16,
                'path' => 'front/assets/img/product/product-16.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 16,
                'path' => 'front/assets/img/product/product-16.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 16,
                'path' => 'front/assets/img/product/product-16.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 16,
                'path' => 'front/assets/img/product/product-16.4.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'path' => 'front/assets/img/product/product-17.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'path' => 'front/assets/img/product/product-17.2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'path' => 'front/assets/img/product/product-17.3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'path' => 'front/assets/img/product/product-17.4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);

        DB::table('users')->insert([
            [
                'id' => 1,
                'first_name' => 'Ngo Manh ',
                'last_name' => 'Son',
                'email' => 'ngomanhson2004txpt@gmail.com',
                'password' => Hash::make('12345678'),
                'level' => 2,
                'description' => null,
                'company_name'=> 'FPT APTECH',
                'country'=> 'Viet Nam',
                'street_address'=> '8A Ton That Huyet',
                'town_city'=> 'Ha Noi',
                'postcode_zip'=> '100000',
                'phone'=> '0929999999',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'first_name' => 'Admin ',
                'last_name' => 'WebSite',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('12345678'),
                'level' => 0,
                'description' => null,
                'company_name'=> 'FPT APTECH',
                'country'=> 'Viet Nam',
                'street_address'=> '8A Ton That Huyet',
                'town_city'=> 'Ha Noi',
                'postcode_zip'=> '100000',
                'phone'=> '0929999999',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('blogs')->insert([
            [
                'id' => 1,
                'user_id' => 1,
                'title' => 'Maintenance process – The most detailed decorative tree care',
                'slug' => Str::slug('Maintenance process – The most detailed decorative tree care'),
                'subtitle' => 'The process, the ways to take care of decorative plants, border plants, ornamental plants, flowering plants, etc., are the most detailed. Hope to help readers have more information in tree care.',
                'image'=> 'front/assets/img/blog/blogpage4.jpg',
                'category'=> 'Take care of plant',
                'content'=> 'Perform unnecessary pruning of branches and branches, remove damaged branches, and give trees a more beautiful and balanced shape.Depending on the growth of the tree, schedule the pruning accordingly, avoiding the breaking of the shade tree, ensuring the aesthetic of the tree. Remove weeds and small grasses around trees and other green areas to avoid competition for nutrients and water for plants and keep green areas clean.For lawns on the premises, weeding always takes a lot of time. The weeding process also needs to pay attention to how to get the entire grass root, to avoid overgrowth.Perform periodic fertilization to provide necessary nutrients for plants, help them grow stronger and have more beautiful leaves, flowers, and fruits. Check and apply fertilizers suitable for each type. plants with the right dose and type of fertilizer for the growing stage.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'user_id' => 1,
                'title' => 'Interior greenery means happiness - peace',
                'slug' => Str::slug('Interior greenery means happiness - peace'),
                'subtitle' => 'Owning a happy potted plant will help homeowners more joy, happiness and warmth. At the same time, happiness is also believed to contribute to resolving conflicts and misunderstandings, bringing warmth and solidarity to the collective.',
                'image'=> 'front/assets/img/blog/blogpage1.jpg',
                'category'=> 'Choose to buy trees',
                'content'=> 'If classified according to the purpose of use, Happiness will have 2 types of trees: Happiness on the table and happiness on the floor.
Happy table or mini happiness has a height of both trees and pots about 30-40cm, suitable for placing desks, document cabinets.
Happy to put the floor, the tree has a height of about 1.6 - 2.0m, depending on the interior space, we can choose potted plants for decoration.
Happy interior decoration should pay attention to choose a location with full light, avoid dark places, secret spaces.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'user_id' => 2,
                'title' => 'Cosmic Bonsai and the Kozumikku or Burton style',
                'slug' => Str::slug('Cosmic Bonsai and the Kozumikku or Burton style'),
                'subtitle' => 'Laurent Darrieux started Bonsai in 1987 with his father, and this passion would never leave him. Parts of this post come from his books named Cosmic Bonsaï. Lets find out more about the Kozumikku or Burton style of Bonsai!',
                'image'=> 'front/assets/img/blog/blogpage6.jpeg',
                'category'=> 'Take care of plant',
                'content'=> 'This convoluted method of shaping, allows us to bypass the natural laws governed by apical force and phototropism – those forces which are governed by solar attraction and natural laws. Emphasis is placed upon the inclusion and repetition of fractal forms typical of trees growing on our star and which will be set aside for the time it takes to form the tree and where it will reside thereafter. It’s important to note that with exception to some of the techniques employed in creating this form which allow it to be uniquely obtained, generally the techniques used to achieve this style are classical methods used within typical bonsai development.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'user_id' => 2,
                'title' => 'DIY: Ficus Bonsai',
                'slug' => Str::slug('DIY: Ficus Bonsai'),
                'subtitle' => 'The Ficus is by far the most popular tree chosen by beginners, as it grows well indoors. Most trees sold as Ficus Bonsai however have obvious flaws that were created during the fast development of these trees. ',
                'image'=> 'front/assets/img/blog/blogpage7.jpeg',
                'category'=> 'Take care of plant',
                'content'=> 'For beginners at the art of Bonsai however, these trees are great; they are strong, can be kept in the living room, grow fast and are quite cheap. But even for the intermediate to advanced bonsai enthusiasts, these trees can be a source of low-budget material to build great bonsai. In this article well show how to develop a refined Bonsai out of a cheap imported Ficus tree. It all started with placing the Ficus tree in a large container and let it grow out unimpeded for 1-2 years. This way, we develop the branches and make sure the tree is healthy before we start working on it.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'user_id' => 2,
                'title' => 'Succulent Bonsai trees',
                'slug' => Str::slug('Succulent Bonsai treesi'),
                'subtitle' => 'Succulent plants thrive in arid climates, and can survive these harsh conditions by storing water in their thick, fleshy leaves and stems. Some species are popular amongst Bonsai enthusiasts as these grow well indoors. ',
                'image'=> 'front/assets/img/blog/blogpage8.jpeg',
                'category'=> 'Take care of plant',
                'content'=> 'Succulents are considered indoor plants in most temperate zones, although they can be grown outdoors in full sun and high temperatures. Do not let temperatures drop below 40 °F (5 °C). They require substantial light, full sun if possible, especially when kept indoors.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'user_id' => 1,
                'title' => 'Making a Juniper Bonsai',
                'slug' => Str::slug('Making a Juniper Bonsai'),
                'subtitle' => 'Learn how to make a Juniper bonsai tree! In this article and video we show you how to prune, wire and repot a Juniper tree of about 20 years old. ',
                'image'=> 'front/assets/img/blog/blogpage9.jpeg',
                'category'=> 'Take care of plant',
                'content'=> 'Bonsai can be created in many different ways, from seeds (which would take at least 5 years before you can start working on your tree) or buying a ready-made Bonsai in an online store. Another way is to purchase nursery stock (from a Bonsai retailer or garden center if you are lucky) that has Bonsai potential. By applying techniques like pruning, wiring and repotting you can turn that nursery stock into a nice looking Bonsai tree!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('blog_comments')->insert([
            [
                'id' => 1,
                'blog_id' => 1,
                'user_id' => 1,
                'email' => 'ngomanhson2004txpt@gmail.com',
                'name' => 'Ngo Manh Son',
                'messages' => 'Rat huu ich',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
